baseURL = "https://jiaobufan.github.io/"
publishDir="docs"
title = "Blonde"
author = "wamo"
languageCode = "en"
DefaultContentLanguage = "en"
ignoreErrors = ["error-remote-getjson"]
enableInlineShortcodes = false
theme = "Blonde"
enableRobotsTXT = true

# Please enable this feature if the site is available in Japanese, Chinese or Korean.
#hasCJKLanguage = true

# If you're using Google Analytics, you can enable this feature.
#googleAnalytics = "G-1234567890"

# Disqus Comment System
#disqusShortname = ""

[params]
# The number of articles to be displayed on a single page.
paginator_pages = "5"

# Enable this if you want the archive list to be in a drop-down format.
archive_dropdown = "false"

[menu]

  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 1

  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 2

  [[menu.main]]
    identifier = "contact"
    name = "Contact"
    url = "/contact/"
    weight = 3

[taxonomies]
category = "categories"
tag = "tags"
archive = "archives"

[privacy]

  [privacy.vimeo]
    disabled = true
    simple = false

  [privacy.twitter]
    disabled = true
    enableDNT = false
    simple = false

  [privacy.instagram]
    disabled = true
    simple = false

  [privacy.youtube]
    disabled = true
    privacyEnhanced = false

[services]

  [services.instagram]
    disableInlineCSS = true

  [services.twitter]
    disableInlineCSS = true

[build]
  writeStats = false
