timeout = 30000
enableInlineShortcodes = false

[taxonomies]
category = "categories"
tag = "tags"
archives = "archives"

[privacy]

  [privacy.vimeo]
    disabled = true
    simple = false

  [privacy.twitter]
    disabled = true
    enableDNT = false
    simple = false
    disableInlineCSS = true

  [privacy.instagram]
    disabled = true
    simple = false

  [privacy.youtube]
    disabled = true
    privacyEnhanced = false
